// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.source.project.domain;

import com.source.project.domain.TranferOfFunds;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TranferOfFunds_Roo_Configurable {
    
    declare @type: TranferOfFunds: @Configurable;
    
}
